import 'package:easy_localization/easy_localization.dart';
import 'package:doctor_final/translation/Local_Key.g.dart';

class AppStrings {
  static String appName = 'Hospital';
  static String noRouteFound = LocaleKeys.noRouteFound.tr();
  static String english = 'English';
  static String theInternationalHospital = LocaleKeys.smartPatient.tr();
  static String yourIdNumber = LocaleKeys.yourIdNumber.tr();
  static String password = LocaleKeys.passport.tr();
  static String forgetPassword = LocaleKeys.forgetPassword.tr();
  static String rememberMe = LocaleKeys.rememberMe.tr();
  static String login = LocaleKeys.login.tr();
  static String dontHaveAccount = LocaleKeys.dontHaveAccount.tr();
  static String haveAnAccount = LocaleKeys.haveAnAccount.tr();
  static String signUp = LocaleKeys.signUp.tr();
  static String fullName = LocaleKeys.fullName.tr();
  static String idType = LocaleKeys.idType.tr();
  static String idNumber = LocaleKeys.idNumber.tr();
  static String mobileNumber = LocaleKeys.mobileNumber.tr();
  static String confirmPassword = LocaleKeys.confirmPassword.tr();
  static String createAnAcc = LocaleKeys.createAnAcc.tr();
  static String clickOnTheCam = LocaleKeys.clickOnTheCam.tr();
  static String nationalId = LocaleKeys.nationalId.tr();
  static String passport = LocaleKeys.passport.tr();
  static String home = LocaleKeys.home.tr();
  static String create = LocaleKeys.create.tr();
  static String welcomeToHos = LocaleKeys.welcomeToHos.tr();
  static String weAppreciate = LocaleKeys.weAppreciate.tr();
  static String wehope = LocaleKeys.wehope.tr();
  static String medicalReport = LocaleKeys.personalData.tr();
  static String showResults = LocaleKeys.showResults.tr();
  static String logOut = LocaleKeys.logOut.tr();
  static String arabic = LocaleKeys.arabic.tr();
  static String skip = LocaleKeys.skip.tr();
  static String onBoardingKey = LocaleKeys.onBoardingKey.tr();
  static String gender = LocaleKeys.gender.tr();
  static String uploadYourId = LocaleKeys.uploadYourId.tr();
  static String homePhone = LocaleKeys.homePhone.tr();
  static String maritalStatus = LocaleKeys.maritalStatus.tr();
  static String insuranceCompany = LocaleKeys.insuranceCompany.tr();
  static String male = LocaleKeys.male.tr();
  static String female = LocaleKeys.female.tr();
  static String uploadPhoto = LocaleKeys.uploadPhoto.tr();
  static String yourAdress = LocaleKeys.yourAdress.tr();
  static String dateOfBirth = LocaleKeys.dateOfBirth.tr();
  static String insuranceNumber = LocaleKeys.insuranceNumber.tr();
  static String labResult = LocaleKeys.labResult.tr();
  static String radiologyResult = LocaleKeys.radiologyResult.tr();
  static String date = LocaleKeys.date.tr();
  static String type = LocaleKeys.type.tr();
  static String testName = LocaleKeys.testName.tr();
  static String shareTo = LocaleKeys.shareTo.tr();
  static String showReport = LocaleKeys.showReport.tr();
  static String showImage = LocaleKeys.showImage.tr();
  static String ctSpines = 'Ct Spines';
  static String inpatent = LocaleKeys.inpatent.tr();
  static String yourDataSuccessfulySaved =
      LocaleKeys.yourDataSuccessfulySaved.tr();
  static String prescritions = LocaleKeys.prescritions.tr();
  static String filter = LocaleKeys.filter.tr();
  static String visits = LocaleKeys.visits.tr();
  static String result = LocaleKeys.result.tr();
  static String visitNumber = LocaleKeys.visitNumber.tr();
  static String fillYourData = LocaleKeys.fillYourData.tr();
  // static const fillYourData = 'Fill Your Data';
}
